services:
  # dispatcher:
  #   build: ./dispatcher-service
  #   ports:
  #     - "8040:8040"
  #   volumes:
  #     - ./dispatcher-service/storage:/app/storage
  #   environment:
  #     - WORKER_URL=http://worker:8041
  #   networks:
  #     - padd-net

  worker:
    build: ./worker-service
    ports:
      - "8041:8041"
    platform: linux/amd64
    volumes:
      - ./dispatcher-service/storage:/app/storage
      - ./worker-service/models:/app/models
    networks:
      - padd-net
    # depends_on:
    #   - dispatcher


networks:
  padd-net:
    driver: bridge